/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package examples;

import examples.tree2d.Tree2D;
import javax.media.opengl.GLCapabilities;
import javax.media.opengl.GLEventListener;
import javax.media.opengl.GLProfile;
import javax.media.opengl.awt.GLCanvas;

/**
 *
 * @author pedro
 */
public class MainFrame extends javax.swing.JFrame
{
	/**
	 * 
	 */
	final private GLCanvas canvas;
	/**
	 * 
	 */
	private Listener listener;
	/**
	 * Creates new form MainFrame
	 */
	public MainFrame ()
	{
		GLProfile glp = GLProfile.getDefault ();
		GLCapabilities caps = new GLCapabilities (glp);
		this.canvas = new GLCanvas (caps);
		this.listener = new Listener (this.canvas);
		canvas.addGLEventListener (this.listener);
		canvas.addKeyListener (this.listener);
		initComponents ();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {
      java.awt.GridBagConstraints gridBagConstraints;

      modelsButtonGroup = new javax.swing.ButtonGroup();
      splitPane = new javax.swing.JSplitPane();
      exampleSelectionPanel = new javax.swing.JPanel();
      kochIslandRadioButton = new javax.swing.JRadioButton();
      jPanel1 = new javax.swing.JPanel();
      jPanel2 = new javax.swing.JPanel();
      tree1RadioButton = new javax.swing.JRadioButton();
      tree2RadioButton = new javax.swing.JRadioButton();
      tree3RadioButton = new javax.swing.JRadioButton();
      jPanel3 = new javax.swing.JPanel();
      tree4RadioButton = new javax.swing.JRadioButton();
      tree5RadioButton = new javax.swing.JRadioButton();
      tree6RadioButton = new javax.swing.JRadioButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setMinimumSize(new java.awt.Dimension(800, 600));
      setPreferredSize(new java.awt.Dimension(800, 600));

      exampleSelectionPanel.setLayout(new java.awt.GridBagLayout());

      modelsButtonGroup.add(kochIslandRadioButton);
      kochIslandRadioButton.setText("koch island");
      kochIslandRadioButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            kochIslandRadioButtonActionPerformed(evt);
         }
      });
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      exampleSelectionPanel.add(kochIslandRadioButton, gridBagConstraints);

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("bracket OL-Systems plants"));
      jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("edge-rewrite"));

      modelsButtonGroup.add(tree1RadioButton);
      tree1RadioButton.setText("tree 1");
      tree1RadioButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            tree1RadioButtonActionPerformed(evt);
         }
      });
      jPanel2.add(tree1RadioButton);

      modelsButtonGroup.add(tree2RadioButton);
      tree2RadioButton.setText("tree 2");
      tree2RadioButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            tree2RadioButtonActionPerformed(evt);
         }
      });
      jPanel2.add(tree2RadioButton);

      modelsButtonGroup.add(tree3RadioButton);
      tree3RadioButton.setText("tree 3");
      tree3RadioButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            tree3RadioButtonActionPerformed(evt);
         }
      });
      jPanel2.add(tree3RadioButton);

      jPanel1.add(jPanel2);

      jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("node-rewrite"));

      modelsButtonGroup.add(tree4RadioButton);
      tree4RadioButton.setText("tree 4");
      tree4RadioButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            tree4RadioButtonActionPerformed(evt);
         }
      });
      jPanel3.add(tree4RadioButton);

      modelsButtonGroup.add(tree5RadioButton);
      tree5RadioButton.setText("tree 5");
      tree5RadioButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            tree5RadioButtonActionPerformed(evt);
         }
      });
      jPanel3.add(tree5RadioButton);

      modelsButtonGroup.add(tree6RadioButton);
      tree6RadioButton.setText("tree 6");
      tree6RadioButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            tree6RadioButtonActionPerformed(evt);
         }
      });
      jPanel3.add(tree6RadioButton);

      jPanel1.add(jPanel3);

      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      exampleSelectionPanel.add(jPanel1, gridBagConstraints);

      splitPane.setLeftComponent(exampleSelectionPanel);

      getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);
      this.splitPane.setRightComponent (this.canvas);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void kochIslandRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_kochIslandRadioButtonActionPerformed
   {//GEN-HEADEREND:event_kochIslandRadioButtonActionPerformed
		this.listener.setDolSystem (new examples.koch.Island ());
   }//GEN-LAST:event_kochIslandRadioButtonActionPerformed

   private void tree2RadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tree2RadioButtonActionPerformed
   {//GEN-HEADEREND:event_tree2RadioButtonActionPerformed
		this.listener.setDolSystem (Tree2D.createTree2 ());
   }//GEN-LAST:event_tree2RadioButtonActionPerformed

   private void tree1RadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tree1RadioButtonActionPerformed
   {//GEN-HEADEREND:event_tree1RadioButtonActionPerformed
		this.listener.setDolSystem (Tree2D.createTree1 ());
   }//GEN-LAST:event_tree1RadioButtonActionPerformed

   private void tree3RadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tree3RadioButtonActionPerformed
   {//GEN-HEADEREND:event_tree3RadioButtonActionPerformed
      this.listener.setDolSystem (Tree2D.createTree3 ());
   }//GEN-LAST:event_tree3RadioButtonActionPerformed

   private void tree4RadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tree4RadioButtonActionPerformed
   {//GEN-HEADEREND:event_tree4RadioButtonActionPerformed
		this.listener.setDolSystem (Tree2D.createTree4 ());
   }//GEN-LAST:event_tree4RadioButtonActionPerformed

   private void tree5RadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tree5RadioButtonActionPerformed
   {//GEN-HEADEREND:event_tree5RadioButtonActionPerformed
      this.listener.setDolSystem (Tree2D.createTree5 ());
   }//GEN-LAST:event_tree5RadioButtonActionPerformed

   private void tree6RadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tree6RadioButtonActionPerformed
   {//GEN-HEADEREND:event_tree6RadioButtonActionPerformed
      this.listener.setDolSystem (Tree2D.createTree6 ());
   }//GEN-LAST:event_tree6RadioButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main (String args[])
	{
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels ()) {
				if ("Nimbus".equals (info.getName ())) {
					javax.swing.UIManager.setLookAndFeel (info.getClassName ());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger (MainFrame.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger (MainFrame.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger (MainFrame.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger (MainFrame.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater (new Runnable ()
		{
			public void run ()
			{
				new MainFrame ().setVisible (true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel exampleSelectionPanel;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JRadioButton kochIslandRadioButton;
   private javax.swing.ButtonGroup modelsButtonGroup;
   private javax.swing.JSplitPane splitPane;
   private javax.swing.JRadioButton tree1RadioButton;
   private javax.swing.JRadioButton tree2RadioButton;
   private javax.swing.JRadioButton tree3RadioButton;
   private javax.swing.JRadioButton tree4RadioButton;
   private javax.swing.JRadioButton tree5RadioButton;
   private javax.swing.JRadioButton tree6RadioButton;
   // End of variables declaration//GEN-END:variables
}
