/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package examples;

import javax.media.opengl.GLCapabilities;
import javax.media.opengl.GLEventListener;
import javax.media.opengl.GLProfile;
import javax.media.opengl.awt.GLCanvas;

/**
 *
 * @author pedro
 */
public class MainFrame extends javax.swing.JFrame
{
	/**
	 * 
	 */
	final private GLCanvas canvas;
	/**
	 * 
	 */
	private Listener listener;
	/**
	 * Creates new form MainFrame
	 */
	public MainFrame ()
	{
		GLProfile glp = GLProfile.getDefault ();
		GLCapabilities caps = new GLCapabilities (glp);
		this.canvas = new GLCanvas (caps);
		this.listener = new Listener (this.canvas);
		canvas.addGLEventListener (this.listener);
		canvas.addKeyListener (this.listener);
		initComponents ();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      splitPane = new javax.swing.JSplitPane();
      exampleSelectionPanel = new javax.swing.JPanel();
      kochIslandRadioButton = new javax.swing.JRadioButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      exampleSelectionPanel.setLayout(new java.awt.GridBagLayout());

      kochIslandRadioButton.setText("koch island");
      kochIslandRadioButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            kochIslandRadioButtonActionPerformed(evt);
         }
      });
      exampleSelectionPanel.add(kochIslandRadioButton, new java.awt.GridBagConstraints());

      splitPane.setLeftComponent(exampleSelectionPanel);

      getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);
      this.splitPane.setRightComponent (this.canvas);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void kochIslandRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_kochIslandRadioButtonActionPerformed
   {//GEN-HEADEREND:event_kochIslandRadioButtonActionPerformed
		this.listener.setDolSystem (new examples.koch.Island ());
   }//GEN-LAST:event_kochIslandRadioButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main (String args[])
	{
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels ()) {
				if ("Nimbus".equals (info.getName ())) {
					javax.swing.UIManager.setLookAndFeel (info.getClassName ());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger (MainFrame.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger (MainFrame.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger (MainFrame.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger (MainFrame.class.getName ()).log (java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater (new Runnable ()
		{
			public void run ()
			{
				new MainFrame ().setVisible (true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel exampleSelectionPanel;
   private javax.swing.JRadioButton kochIslandRadioButton;
   private javax.swing.JSplitPane splitPane;
   // End of variables declaration//GEN-END:variables
}
